// source: download.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.zhst.ImgServiceErrCode', null, global);
goog.exportSymbol('proto.zhst.ImgServiceMsg', null, global);
goog.exportSymbol('proto.zhst.ImgServiceRequestType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.zhst.ImgServiceMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.zhst.ImgServiceMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.zhst.ImgServiceMsg.displayName = 'proto.zhst.ImgServiceMsg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.zhst.ImgServiceMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.zhst.ImgServiceMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.zhst.ImgServiceMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zhst.ImgServiceMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorCode: jspb.Message.getFieldWithDefault(msg, 2, 0),
    taskid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    columnFamilyName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    uuid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    imgData: msg.getImgData_asB64(),
    daytime: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.zhst.ImgServiceMsg}
 */
proto.zhst.ImgServiceMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.zhst.ImgServiceMsg;
  return proto.zhst.ImgServiceMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.zhst.ImgServiceMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.zhst.ImgServiceMsg}
 */
proto.zhst.ImgServiceMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.zhst.ImgServiceRequestType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!proto.zhst.ImgServiceErrCode} */ (reader.readEnum());
      msg.setErrorCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTaskid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setColumnFamilyName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 6:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImgData(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDaytime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.zhst.ImgServiceMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.zhst.ImgServiceMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.zhst.ImgServiceMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.zhst.ImgServiceMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getErrorCode();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTaskid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getColumnFamilyName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getImgData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      6,
      f
    );
  }
  f = message.getDaytime();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional ImgServiceRequestType type = 1;
 * @return {!proto.zhst.ImgServiceRequestType}
 */
proto.zhst.ImgServiceMsg.prototype.getType = function() {
  return /** @type {!proto.zhst.ImgServiceRequestType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.zhst.ImgServiceRequestType} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional ImgServiceErrCode error_code = 2;
 * @return {!proto.zhst.ImgServiceErrCode}
 */
proto.zhst.ImgServiceMsg.prototype.getErrorCode = function() {
  return /** @type {!proto.zhst.ImgServiceErrCode} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.zhst.ImgServiceErrCode} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setErrorCode = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string taskid = 3;
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getTaskid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setTaskid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string column_family_name = 4;
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getColumnFamilyName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setColumnFamilyName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string uuid = 5;
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional bytes img_data = 6;
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getImgData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * optional bytes img_data = 6;
 * This is a type-conversion wrapper around `getImgData()`
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getImgData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImgData()));
};


/**
 * optional bytes img_data = 6;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImgData()`
 * @return {!Uint8Array}
 */
proto.zhst.ImgServiceMsg.prototype.getImgData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImgData()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setImgData = function(value) {
  return jspb.Message.setProto3BytesField(this, 6, value);
};


/**
 * optional string daytime = 7;
 * @return {string}
 */
proto.zhst.ImgServiceMsg.prototype.getDaytime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.zhst.ImgServiceMsg} returns this
 */
proto.zhst.ImgServiceMsg.prototype.setDaytime = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.zhst.ImgServiceErrCode = {
  IMG_ERRORCODE_SUCCESS: 0,
  IMG_ERRORCODE_FAILED: 1
};

/**
 * @enum {number}
 */
proto.zhst.ImgServiceRequestType = {
  PUT_REQUEST: 0,
  GET_REQUEST: 1,
  DELETE_COLUMN_FAMILY_REQUEST: 2,
  DELETE_TASK_REQUEST: 3
};

goog.object.extend(exports, proto.zhst);
